# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e513b4716cc9542ac4c1a1f06be7fb500e014087cd5a4a5ec42ab817f0208d0079507f813ad74ae3a21a7b7478d50c36be8e65724007ceddfdf11a661a60b274

test:
  secret_key_base: 17ff1dc919b71603601814287e0a26c2527243c9d5b04bb673e4f617a60eaeb297bc7e1e1f606cb3798eaefa414087fff9ab78e62cc723bed3697360dc52dd57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
